document.write('<ul class="flipMenu">');
document.write('<li><a href="javascript:;">HTML</a>');
document.write('  <ul>');
document.write('   	<li><a href="html1.html">Osnovno o HTMLu</a></li>');
document.write('   	<li><a href="html2.html" >HTML i tablice</a></li>');
document.write('  </ul>');
document.write('</li>');
document.write('<li><a href="javascript:;">CSS</a>');
document.write('  <ul>');
document.write('    <li><a href="css1.html">HTML protiv CSSa</a></li>');
document.write('    <li><a href="css2.html">Stiliziranje CSSom</a></li>');
document.write('    <li><a href="css3.html">Pozicioniranje CSSom</a></li>');
document.write('    <li><a href="css4.html">CSS i liste</a></li>');
document.write('  </ul>');
document.write('</li>');
document.write('<li><a href="javascript:;">Javascript</a>');
document.write('  <ul>');
document.write('    <li><a href="javascript1.html">Osnovno o Javascriptu</a></li>');
document.write('    <li><a href="javascript2.html">Javascript èarobnjaci</a></li>');
document.write('  </ul>');
document.write('</li>');
document.write('<li><a href="javascript:;">PHP</a>');
document.write('  <ul>');
document.write('    <li><a href="php1.html">Najosnovnije osnove</a></li>');
document.write('    <li><a href="php2.html">Osnovni princip rada</a></li>');
document.write('    <li><a href="php3.html">PHP kroz primjere</a></li>');
document.write('    <li><a href="php4.html">Slanje i prihvat podataka</a></li>');
document.write('    <li><a href="php5.html">Primjer: knjiga gostiju</a></li>');
document.write('  </ul>');
document.write('</li>');
document.write('<li><a href="javascript:;">Flash</a>');
document.write('  <ul>');
document.write('    <li><a href="flash1.html">Snala¾enje u Flashu</a></li>');
document.write('  </ul>');
document.write('</li>');
document.write('<li><a href="javascript:closeAllFlips()">sakrij sve</a></li>');
document.write('<li><a href="javascript:openAllFlips()">prika¾i sve</a></li>');
document.write('</ul>');